### ISSUE TITLE
Bower install ENOTFOUND

### ISSUE THREAD

**Issue by fgagneten** [OSAMES/ionic-datepicker#8]
Hey guys! Thanks a lot for your hard-working every days!
I'm trying to do:

    bower install ionic-datepicker-fork-ionic1 --save

and get: 

> bower                        ENOTFOUND Package ionic-datepicker-fork-ionic1 not found

I just want to get the last code from this change: 

[Click Me](https://github.com/OSAMES/ionic-datepicker/issues/7)

Thanks!

**Comment by postb99** [comment]
Hi Faustino, I will check this, it's embarrassing. 

However, since the version 1.6 is midway fixes you have to install the bundle (minified version in dist folder) for now, from my link on issue 7.

I get back to you but not until Tuesday. I will test it first though. 

Thank you.

**Comment by Xarkam** [comment]
Bower is marked deprecated.
![image](https://cloud.githubusercontent.com/assets/331816/26765534/ef1fe48e-497d-11e7-9cd4-be5f5a80b95e.png) and it's marked on the website.

Yarn find the ionic-datepicker-fork-ionic1 but you need to learn Yarn functionality.

**Comment by postb99** [comment]
I noticed that the package was not registered anymore in bower repository. I modified the bower.json file from the warnings I got when registering the package again.

Today I checked that the package is still registered and available. However, the version number is 1.6.3 now rather than 1.6.0 with no change excepted in bower.json :p
